---
- name: nextcloud docker directories exist
  file:
    path: '{{ item }}'
    state: directory
  loop:
    - '{{ nextcloud_docker_directory }}'
    - '{{ nextcloud_docker_directory }}/db'

- name: nextcloud mariadb docker container
  docker_container:
    name: nextcloud-db
    image: mariadb
    pull: true
    volumes:
      - '{{ nextcloud_docker_directory }}/db:/var/lib/mysql:rw'
    env:
      MYSQL_DATABASE: 'nextcloud'
      MYSQL_USER: '{{ nextcloud_db_user }}'
      MYSQL_PASSWORD: '{{ nextcloud_db_user_password }}'
      MYSQL_ROOT_PASSWORD: '{{ nextcloud_db_root_password }}'
      MYSQL_HOST: "{{ nextcloud_db_host | default('127.0.0.1') }}"
    restart_policy: unless-stopped
    memory: '{{ nextcloud_db_memory }}'