---
- name: nextcloud docker directories exist
  file:
    path: '{{ item }}'
    state: directory
  loop:
    - '{{ nextcloud_docker_directory }}'
    - '{{ nextcloud_docker_directory }}/db'

- name: nextcloud mariadb docker container
  docker_container:
    name: nextdb
    image: mariadb
    pull: true
    # memory: '{{ nextcloud_db_memory }}'
    volumes:
      - '{{ nextcloud_docker_directory }}/db:/var/lib/mysql:rw'
    # ports:
    #   - '{{ nextcloud_db_port }}:3306'
    networks:
      - name: '{{ traefik_docker_network | default(bridge) }}'
    # links:
    #   - next
    networks_cli_compatible: true
    restart_policy: unless-stopped
    env:
      MYSQL_DATABASE: 'nextcloud'
      MYSQL_USER: '{{ nextcloud_db_user }}'
      MYSQL_PASSWORD: '{{ nextcloud_db_user_passwd }}'
      MYSQL_ROOT_PASSWORD: '{{ nextcloud_db_root_passwd }}'
